print(" ")
print("----Start of Output ---------------------------")
print(" ")
print("Hello World")
name = input("What is your name ? ") 
print("Goodbye "+ name)
print("")
print("----End of Output -----------------------------")
print(" ")
print(" ")
print(" ")

